import { Badge, Button, Card, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Textarea } from "@alawein/ui";
import { useState } from 'react';





import { Swords, Play, RotateCcw, Crown, Timer, MessageSquare } from 'lucide-react';

interface Message {
  id: string;
  role: 'proponent' | 'skeptic' | 'system';
  content: string;
  timestamp: Date;
  model?: string;
  citations?: string[];
}

const DEMO_NOTICE =
  'Scripted demo — no provider calls or verified citations. Responses and scores are illustrative only.';

export const DebateMode = () => {
  const [topic, setTopic] = useState('');
  const [proponentModel, setProponentModel] = useState('');
  const [skepticModel, setSkepticModel] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [isRunning, setIsRunning] = useState(false);
  const [currentRound, setCurrentRound] = useState(0);
  const [scores, setScores] = useState({ proponent: 0, skeptic: 0 });

  const models = ['GPT-4o', 'Claude 3.5 Sonnet', 'Gemini 1.5 Pro', 'Llama 3.1 70B'];

  const mockDebateTopics = [
    'Nuclear fusion is the best long-term solution to the energy crisis',
    'AI should be regulated at the international level',
    'Remote work is more beneficial than in-person work for most companies',
    'Universal Basic Income should be implemented globally',
  ];

  const startDebate = async () => {
    if (!topic || !proponentModel || !skepticModel) return;

    setIsRunning(true);
    setCurrentRound(1);
    setMessages([
      {
        id: 'system-start',
        role: 'system',
        content: `Debate started: "${topic}"\nProponent (${proponentModel}) vs Skeptic (${skepticModel})\nRound 1 of 3`,
        timestamp: new Date(),
      },
    ]);

    // This screen intentionally demonstrates the interaction design without calling a provider.
    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        {
          id: 'msg-1',
          role: 'proponent',
          content: `Illustrative sample response for ${topic.toLowerCase()}. This scripted argument demonstrates the proponent layout only; it is not generated by ${proponentModel} and does not cite external research.`,
          timestamp: new Date(),
          model: proponentModel,
          citations: ['Illustrative citation placeholder — not a verified source'],
        },
      ]);
    }, 1500);

    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        {
          id: 'msg-2',
          role: 'skeptic',
          content:
            'Illustrative sample response showing the skeptic layout. This text is scripted, is not generated by the selected model, and makes no evidence claim.',
          timestamp: new Date(),
          model: skepticModel,
          citations: ['Illustrative citation placeholder — not a verified source'],
        },
      ]);
    }, 3000);

    setTimeout(() => {
      setScores({ proponent: 85, skeptic: 78 });
      setCurrentRound(2);
    }, 4500);
  };

  const resetDebate = () => {
    setMessages([]);
    setIsRunning(false);
    setCurrentRound(0);
    setScores({ proponent: 0, skeptic: 0 });
  };

  return (
    <div className="space-y-6">
      {/* Configuration Panel */}
      <Card className="p-6 gradient-surface border-trust/20 hover:border-trust/40 transition-colors">
        <div className="flex items-center gap-2 mb-4">
          <Swords className="h-5 w-5 text-trust" />
          <h3 className="text-lg font-bold text-foreground">Demo Configuration</h3>
          <Badge className="bg-trust/10 text-trust">Scripted Demo</Badge>
        </div>
        <p className="mb-4 text-sm text-muted-foreground">{DEMO_NOTICE}</p>

        <div className="grid md:grid-cols-2 gap-4 mb-4">
          <div>
            <div className="text-sm font-medium text-foreground mb-2">Proponent Model</div>
            <Select value={proponentModel} onValueChange={setProponentModel}>
              <SelectTrigger>
                <SelectValue placeholder="Select proponent model" />
              </SelectTrigger>
              <SelectContent>
                {models.map((model) => (
                  <SelectItem key={model} value={model}>
                    {model}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <div className="text-sm font-medium text-foreground mb-2">Skeptic Model</div>
            <Select value={skepticModel} onValueChange={setSkepticModel}>
              <SelectTrigger>
                <SelectValue placeholder="Select skeptic model" />
              </SelectTrigger>
              <SelectContent>
                {models.map((model) => (
                  <SelectItem key={model} value={model}>
                    {model}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="mb-4">
          <div className="text-sm font-medium text-foreground mb-2">Debate Topic</div>
          <Textarea
            placeholder="Enter a debatable topic or select from suggestions below..."
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            className="min-h-20"
          />
          <div className="flex flex-wrap gap-2 mt-2">
            {mockDebateTopics.map((suggestion) => (
              <Button
                key={suggestion}
                variant="outline"
                size="sm"
                onClick={() => setTopic(suggestion)}
                className="text-xs"
              >
                {suggestion}
              </Button>
            ))}
          </div>
        </div>

        <div className="flex gap-2">
          <Button
            onClick={startDebate}
            disabled={!topic || !proponentModel || !skepticModel || isRunning}
            variant="hero"
            className="hover-scale"
          >
            <Play className="h-4 w-4" />
            Run Scripted Demo
          </Button>
          <Button
            onClick={resetDebate}
            variant="outline"
            className="hover:border-risk hover:text-risk"
          >
            <RotateCcw className="h-4 w-4" />
            Reset Arena
          </Button>
        </div>
      </Card>

      {/* Debate Arena */}
      {messages.length > 0 && (
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Conversation */}
          <div className="lg:col-span-2">
            <Card className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-bold text-foreground">Scripted Debate Demo</h3>
                {isRunning && (
                  <div className="flex items-center gap-2">
                    <Timer className="h-4 w-4 text-accent animate-pulse" />
                    <span className="text-sm text-accent">Scripted round {currentRound} of 3</span>
                  </div>
                )}
              </div>

              <div className="space-y-4 max-h-150 overflow-y-auto">
                {messages.map((message) => (
                  <div key={message.id} className="animate-fade-in">
                    {message.role === 'system' ? (
                      <div className="text-center py-2">
                        <Badge variant="secondary">{message.content}</Badge>
                      </div>
                    ) : (
                      <Card
                        className={`p-4 ${
                          message.role === 'proponent'
                            ? 'border-l-4 border-l-accent bg-accent/5'
                            : 'border-l-4 border-l-primary bg-primary/5'
                        }`}
                      >
                        <div className="flex items-center gap-2 mb-2">
                          <Badge
                            className={
                              message.role === 'proponent'
                                ? 'bg-accent/10 text-accent'
                                : 'bg-primary/10 text-primary'
                            }
                          >
                            {message.role === 'proponent' ? 'Proponent' : 'Skeptic'}
                          </Badge>
                          <span className="text-sm text-muted-foreground">{message.model}</span>
                        </div>
                        <p className="text-foreground whitespace-pre-line">{message.content}</p>
                        {message.citations && (
                          <div className="mt-2 pt-2 border-t border-border">
                            <div className="text-xs text-muted-foreground">
                              <strong>Citations:</strong> {message.citations.join(', ')}
                            </div>
                          </div>
                        )}
                      </Card>
                    )}
                  </div>
                ))}
              </div>
            </Card>
          </div>

          {/* Scoring Panel */}
          <div className="space-y-4">
            <Card className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <Crown className="h-5 w-5 text-accent" />
                <h3 className="text-lg font-bold text-foreground">Illustrative Score Display</h3>
              </div>

              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-foreground">
                    Proponent ({proponentModel})
                  </span>
                  <Badge className="bg-accent/10 text-accent">{scores.proponent}/100</Badge>
                </div>
                <div className="w-full bg-muted rounded-full h-2">
                  <div
                    className="bg-accent h-2 rounded-full transition-all duration-500"
                    style={{ width: `${scores.proponent}%` }}
                  ></div>
                </div>

                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-foreground">
                    Skeptic ({skepticModel})
                  </span>
                  <Badge className="bg-primary/10 text-primary">{scores.skeptic}/100</Badge>
                </div>
                <div className="w-full bg-muted rounded-full h-2">
                  <div
                    className="bg-primary h-2 rounded-full transition-all duration-500"
                    style={{ width: `${scores.skeptic}%` }}
                  ></div>
                </div>
              </div>

              <div className="mt-4 pt-4 border-t border-border">
                <h4 className="text-sm font-medium text-foreground mb-2">Demo Scoring Criteria</h4>
                <div className="space-y-1 text-xs text-muted-foreground">
                  <div>Scores are scripted display values, not measured model results.</div>
                  <div>• Logical consistency</div>
                  <div>• Factual accuracy</div>
                  <div>• Citation quality</div>
                  <div>• Persuasiveness</div>
                </div>
              </div>
            </Card>

            <Card className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <MessageSquare className="h-5 w-5 text-primary" />
                <h3 className="text-lg font-bold text-foreground">Illustrative Arbiter Notes</h3>
              </div>
              <div className="text-sm text-muted-foreground space-y-2">
                <p>• This note set demonstrates the review layout only.</p>
                <p>• It is not generated by either selected model.</p>
                <p>• No displayed citation has been verified.</p>
              </div>
            </Card>
          </div>
        </div>
      )}
    </div>
  );
};
