// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://xzuylggvftuglkdhnljs.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dXlsZ2d2ZnR1Z2xrZGhubGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NzYxNjEsImV4cCI6MjA3MDQ1MjE2MX0.d4KTj3jiS-OKDz1f1QqtAnsg7GQxIVtToJyNqwpCQy0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
